[workspace]
authors = ["Gregory Tucker <gregory.tucker@ess.eu>"]
channels = ["conda-forge"]
name = "ess-ecdc-dev"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CONAN_USER_HOME="$PIXI_PROJECT_ROOT"

[tasks]

[dependencies]
cmake = "<4"
c-compiler = "<1.7"
cxx-compiler = "<1.7"
libxcrypt = ">=4.4.36,<5"
qt6-main = ">=6.9.0,<7"
libgl-devel = ">=1.7.0,<2"
mcstas = ">=3.5.27,<4"
ninja = ">=1.12.1,<2"
gdb = "<15.3"
make = ">=4.4.1,<5"
